### ISSUE TITLE
in release model not working

### ISSUE THREAD

**Issue by iusn** [flyrboy96/flutter_dropdown_banner#1]
thank you for this awesome package

I have a problem,
in my main.dart code

`    return MaterialApp(
      theme: ThemeData(
        primaryColor: GColor.primary,
      ),
      home:DropdownBanner(child: App(), navigatorKey: _navigatorKey)
    );
  }`

other page code
` _bannerNot() {
    DropdownBanner.showBanner(
        text: 'Failed to complete network request',
        color: Colors.red,
        textStyle: TextStyle(color: Colors.white),
        tapCallback: _counterFunction);
  }`

in debug mode it`s working well
bug in release it`s not working
my environment

`[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/nero/Documents/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nero/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0`

thank you

**Comment by flyrboy96** [comment]
iusn I noticed this as well. From what I can tell it works in debug for ios and android, and release for android, but does not work for debug in android. Would you say this is correct?

**Comment by bruce-brookshire** [comment]
@iusn It is possible that the latest version [1.2.0](https://pub.dev/packages/dropdown_banner#-changelog-tab-) might actually address the fix for this. I am testing release later today for this and will report back

**Comment by bruce-brookshire** [comment]
confirmed that v1.2.0 fixes this issue in commit eb02a29ff89c79ed0dd1b8e3c6560b51706774ee
