### ISSUE TITLE
Adding 'navigatorKey' GlobalKey interrupting back button in Android.

### ISSUE THREAD

**Issue by hubdestro** [flyrboy96/flutter_dropdown_banner#3]
Look at the below code snippet.

```
final navigatorKey = GlobalKey<NavigatorState>();
DropdownBanner(
        child: getContentWidget(context),
        navigatorKey: navigatorKey,
      );

```
Now when I press the back button in Android, Application quit.
But when I remove above code its works fine.

**Comment by bruce-brookshire** [comment]
@hubdestro 

Sorry for the delay. I was on Vacay! Does this happen on iOS as well?

**Comment by flyrboy96** [comment]
@hubdestro
